export const GET_ACCESS_TOKEN_REQUEST = "GET_ACCESS_TOKEN_REQUEST";
export const GET_ACCESS_TOKEN_SUCCESS = "GET_ACCESS_TOKEN_SUCCESS";
export const GET_ACCESS_TOKEN_FAILED = "GET_ACCESS_TOKEN_FAILED";

export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAILED = "GET_USER_PROFILE_FAILED";

export const GET_USER_MEDIA_ID_REQUEST = "GET_USER_MEDIA_ID_REQUEST";
export const GET_USER_MEDIA_ID_SUCCESS = "GET_USER_MEDIA_ID_SUCCESS";
export const GET_USER_MEDIA_ID_FAILED = "GET_USER_MEDIA_ID_FAILED";

export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAILED = "GET_POST_FAILED";
